spring.application.name=LibraryApplication
# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/librarydb
spring.datasource.username=library_db_username
spring.datasource.password=1234

# Hibernate and JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true